# Cloud Build configuration for deploying to Cloud Run

substitutions:
  _NEXT_PUBLIC_SUPABASE_URL: 'https://oqrvutvyyscvacmxvpkk.supabase.co'
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xcnZ1dHZ5eXNjdmFjbXh2cGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxMDk3MzMsImV4cCI6MjA4MDY4NTczM30.UiRFHGVNaKWYdyyUsRmc8VQGfH0Z_EX5mOHOz5a_fwI'
  _NEXT_PUBLIC_BASE_URL: 'https://nextlevel-career-site-rxoneg3z6a-an.a.run.app'
  _NEXT_PUBLIC_SITE_URL: 'https://nextlevel-career-site-rxoneg3z6a-an.a.run.app'

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nextlevel-career-site:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nextlevel-career-site:latest'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/nextlevel-career-site:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nextlevel-career-site'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nextlevel-career-site:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_SUPABASE_URL=$_NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY=$_NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_BASE_URL=$_NEXT_PUBLIC_BASE_URL,NEXT_PUBLIC_SITE_URL=$_NEXT_PUBLIC_SITE_URL'
      - '--set-secrets'
      - 'SUPABASE_SERVICE_ROLE_KEY=supabase-service-role-key:latest,GEMINI_API_KEY=gemini-api-key:latest,RESEND_API_KEY=resend-api-key:latest'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/nextlevel-career-site:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/nextlevel-career-site:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
